# Generated by Django 5.1.2 on 2024-11-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unitrader', '0003_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_images',
        ),
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to='item_images/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
