# Generated by Django 5.1.2 on 2024-11-04 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unitrader', '0007_message_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='coins',
            field=models.IntegerField(default=500),
        ),
    ]
