# Generated by Django 5.1.2 on 2024-11-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unitrader', '0011_alter_item_bidding_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='bidding_end_time',
            field=models.DateTimeField(),
        ),
    ]
