# Generated by Django 5.1.2 on 2024-11-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unitrader', '0013_alter_item_bidding_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
